//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YYT_DBEntities : DbContext
    {
        public YYT_DBEntities()
            : base("name=YYT_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HT_Account> HT_Account { get; set; }
        public virtual DbSet<HT_Menu> HT_Menu { get; set; }
        public virtual DbSet<HT_UserGroup> HT_UserGroup { get; set; }
        public virtual DbSet<Luck_Activity> Luck_Activity { get; set; }
        public virtual DbSet<Luck_ActivityJackpot> Luck_ActivityJackpot { get; set; }
        public virtual DbSet<Luck_ActivityPrize> Luck_ActivityPrize { get; set; }
        public virtual DbSet<QD_Channel> QD_Channel { get; set; }
        public virtual DbSet<QD_ChannelLog> QD_ChannelLog { get; set; }
        public virtual DbSet<QD_ChanneWhilte> QD_ChanneWhilte { get; set; }
        public virtual DbSet<Wx_Config> Wx_Config { get; set; }
        public virtual DbSet<Wx_Redpack> Wx_Redpack { get; set; }
        public virtual DbSet<Wx_RedpackLog> Wx_RedpackLog { get; set; }
        public virtual DbSet<WxCompany_Payment> WxCompany_Payment { get; set; }
        public virtual DbSet<WxCompany_PaymentLog> WxCompany_PaymentLog { get; set; }
        public virtual DbSet<YYT_Member> YYT_Member { get; set; }
        public virtual DbSet<QD_ChannelUser> QD_ChannelUser { get; set; }
    }
}
