//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Menu
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> isMenu { get; set; }
        public string Droit { get; set; }
        public string Url { get; set; }
        public int SortId { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
