//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luck_Activity
    {
        public int id { get; set; }
        public Nullable<int> channelUserId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> Rules { get; set; }
        public string Img { get; set; }
        public string Url { get; set; }
        public Nullable<int> Status { get; set; }
        public string Introduction { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> maxNum { get; set; }
    }
}
