//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Luck_ActivityJackpot
    {
        public int id { get; set; }
        public Nullable<int> channelUserId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> PrizeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Ip { get; set; }
        public string data_type { get; set; }
        public string out_id { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<System.DateTime> UpdateAddtime { get; set; }

        /// <summary>
        /// 领取总数
        /// </summary>
        [NotMapped]
        public int NotReceiveTotal { get; set; }
    }
}
