//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luck_ActivityPrize
    {
        public int Id { get; set; }
        public Nullable<int> channelUserId { get; set; }
        public string name { get; set; }
        public Nullable<int> sortid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> PrizeType { get; set; }
        public string PrizeLevel { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> winNum { get; set; }
        public string PrizeUrl { get; set; }
        public string PrizeImg { get; set; }
        public Nullable<int> Status { get; set; }
        public string Introduction { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> Position { get; set; }
        public string PositionImg { get; set; }
    }
}
