//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QD_ChannelLog
    {
        public long id { get; set; }
        public string channelName { get; set; }
        public string @interface { get; set; }
        public Nullable<int> status { get; set; }
        public string failType { get; set; }
        public string failMessage { get; set; }
        public string RawData { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    }
}
