//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YYT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wx_Config
    {
        public int Id { get; set; }
        public Nullable<int> channelUserId { get; set; }
        public string wxappid { get; set; }
        public string mch_id { get; set; }
        public string wxkey { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string access_token { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string appSecret { get; set; }
    }
}
